name: Build Sonic 1 and 2 for multiple platforms
on:
  push:
    branches:
      - master
      - main
      - win-actions
      - psvita

jobs:
  v4-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1
      - name: Download SDL2
        run: |
          wget https://libsdl.org/release/SDL2-devel-2.0.14-VC.zip -OutFile SDL2.zip
          mkdir ./dependencies/windows/SDL2
          Expand-Archive -Path SDL2.zip -DestinationPath ./dependencies/windows/SDL2
      - name: Download libogg
        run : |
          wget https://downloads.xiph.org/releases/ogg/libogg-1.3.4.zip -OutFile libogg.zip
          mkdir ./dependencies/windows/libogg
          Expand-Archive -Path libogg.zip -DestinationPath ./dependencies/windows/libogg
      - name: Download libvorbis
        run : |
          wget https://downloads.xiph.org/releases/vorbis/libvorbis-1.3.7.zip -OutFile libvorbis.zip
          mkdir ./dependencies/windows/libborbis
          Expand-Archive -Path libvorbis.zip -DestinationPath ./dependencies/windows/libvorbis
      - name: Run MSBuild
        run: |
          msbuild Sonic12Decomp.sln /p:Configuration=Release /p:Platform=x86  
      - name: Move artifacts
        run: |
          mkdir artifacts
          move ./build/Win32/Release/*.dll ./artifacts 
          move ./build/Win32/Release/*.exe ./artifacts
      - name: Upload artifacts
        uses: actions/upload-artifact@v1.0.0  
        with:
          name: Sonic12-Windows 
          path: artifacts      
  sonic1-psvita:
    runs-on: ubuntu-latest
    container: vitasdk/vitasdk:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install dependencies
        run: apk add --no-cache make cmake
      - name: Build Sonic 1
        run: |
          cd Sonic1.Vita
          cmake .
          make
      - name: Upload VPK
        uses: actions/upload-artifact@v2
        with:
          name: Sonic1-vita
          path: Sonic1.Vita/Sonic1.vpk
          if-no-files-found: error
  sonic2-psvita:
    runs-on: ubuntu-latest
    container: vitasdk/vitasdk:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install dependencies
        run: apk add --no-cache make cmake
      - name: Build Sonic 2
        run: |
          cd Sonic2.Vita
          cmake .
          make
      - name: Upload VPK
        uses: actions/upload-artifact@v2
        with:
          name: sonic2-vita
          path: Sonic2.Vita/Sonic2.vpk
          if-no-files-found: error
